[[news]]
date = "2026-04"
content = "I was awarded the CAA Outstanding Master's Thesis Award in 2025.🎉"

[[news]]
date = "2026-03"
content = "My first paper as the corresponding author has been accepted by ICME 2026! 🎉"


[[news]]
date = "2026-01"
content = "My new paper was accepted by ICRA 2026! 🎉"


[[news]]
date = "2025-10"
content = "I was invited by Prof. Weijia Yao (https://weijia-yao.github.io/index.html) to give a speech in workshop about guiding vector field in IROS 2025."


[[news]]
date = "2025-08"
content = "I attended MRS 2025 Summer School in Prague, Czech Republic."


[[news]]
date = "2024-09"
content = "I started my PhD journey."

[[news]]
date = "2024-07"
content = "A regular paper whose first author is me has been accepted by Automatica. 🎉"