type = "card"
title = "Teaching"
description = "Courses I have taught or assisted with."

[[items]]
title = " Mathmatical Foundation of Reinforcement Learning"
subtitle = "Teaching Assistant"
date = "2025"
content = "url: https://github.com/MathFoundationRL/Book-Mathmatical-Foundation-of-Reinforcement-Learning. This is the famous course given by Prof. Shiyu Zhao (My PhD advisor)."
tags = ["PhD Courses", "Computer Science"]

[[items]]
title = " Principles of Automatic Control"
subtitle = "Teaching Assistant"
date = "2022 & 2023"
content = "A required course at the School of Automation, Beihang University, and a national-level excellent course, it mainly covers state-space equations and Lyapunov stability analysis."
tags = ["Undergraduate", "Automation"]

[[items]]
title = "Theoretical Mechanics"
subtitle = "Teaching Assistant"
date = "2021"
content = "A required course at the School of Automation, Beihang University, and a national-level excellent course, it mainly covers statics, dynamics, and analytical mechanics, including the Lagrange and Hamilton equations, with content involving rigid body mechanics and a small portion of second-order vibration dynamics."
tags = ["Undergraduate", "Mechanics"]