type = "card"
title = "奖项"
description = "我获得的荣誉与奖项。"

[[items]]
title = "中国自动化学会优秀硕士学位论文奖"
subtitle = "中国自动化学会"
date = "2025"
content = "由中国自动化学会颁发，北京，中国。"

[[items]]
title = "助航之星——最佳助教奖"
subtitle = "北京航空航天大学北航学院"
date = "2021"
content = "因优秀的助教表现而获得表彰。"
