[[news]]
date = "2026-04"
content = "荣获2025年中国自动化学会优秀硕士学位论文奖 🎉"

[[news]]
date = "2026-03"
content = "作为通讯作者的首篇论文被 ICME 2026 接收！🎉"

[[news]]
date = "2026-01"
content = "新论文被 ICRA 2026 接收！🎉"

[[news]]
date = "2025-10"
content = "受姚伟嘉教授(https://weijia-yao.github.io/index.html)邀请，在 IROS 2025 研讨会上作指导向量场专题报告。"

[[news]]
date = "2025-08"
content = "参加在捷克布拉格举办的 MRS 2025 暑期学校。"

[[news]]
date = "2024-09"
content = "开始博士研究生生涯。"

[[news]]
date = "2024-07"
content = "以我为第一作者的论文被 Automatica 正式接收！🎉"
